# Generated by Django 4.2.1 on 2023-05-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=255)),
                ('feels_like', models.CharField(max_length=255)),
                ('temp_min', models.CharField(max_length=255)),
                ('temp_max', models.CharField(max_length=255)),
                ('pressure', models.CharField(max_length=255)),
                ('humidity', models.CharField(max_length=255)),
            ],
        ),
    ]
